import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*;

public class cancelhotel2 extends HttpServlet {

    public void init(ServletConfig config)
    	throws ServletException {
    		super.init(config);
    	}
    
    public void doGet(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        out.println("<html>");
        out.println("<body>");
        out.println("<head>");
        out.println("<title>Hello World!</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1>Hello World!</h1>");
        out.println("Your request was"+ request.getMethod()+"\n");
        out.println("</body>");
        out.println("</html>");
    }
    public void doPost(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        Connection c=null;
        String loginid=request.getParameter("loginid");
        String pswd=request.getParameter("pswd");
        String reqno = request.getParameter("reqno");
        int r = Integer.parseInt(reqno);
        int k=0;
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
  		try{
   			Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            c= DriverManager.getConnection("jdbc:odbc:ITMNGMNT","grandtour","grandtour");
            Statement st =c.createStatement();
            
           
            //ResultSet rs1 = st.executeQuery("select * from hotelbooking where reqno = 529");
            String query = new String("select * from Customer where loginid='" +loginid+ "'" ); 
            ResultSet rs= st.executeQuery(query);
            if(rs.next())
               k=1;
            if(k==1)
            {
            	if(!pswd.equals(rs.getString("pswd")))
            	{
            		out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
				out.println("<html>");
				out.println("<head>");
				out.println("<title>Untitled Document</title>");
				out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
				out.println("<SCRIPT>");
				out.println("/*function doClear()");
				out.println("{		 ");
				out.println("document.mainform.loginid.value =\"\"");
				out.println("document.mainform.password.value = \"\";");
				out.println("}*/");
				out.println("function doSubmit()");
				out.println("{");
				out.println("var strErrMsg;");
				out.println("strErrMsg = \"\";			");
				out.println("strErrMsg = doValidations();");
				out.println("if (strErrMsg == \"\" )");
				out.println("{				");
				out.println("document.mainform.action = \"http://localhost:2008/examples/servlet/cancelhotel2\";		");
				out.println("document.mainform.submit();");
				out.println("}");
				out.println("else");
				out.println("{alert(strErrMsg);}");
				out.println("}");
				out.println("function doValidations()");
				out.println("{");
				out.println("var strFld;");
				out.println("var frmDoc;");
				out.println("var strErrMsg;");
				out.println("strErrMsg = \"\";");
				out.println("frmDoc = document.mainform;			");
				out.println("strFld = frmDoc.loginid");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"login-id can not be null\\n\";			");
				out.println("strFld = frmDoc.pswd");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"password can not be null\\n\";	");
				out.println("strFld = frmDoc.reqno");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"req-no can not be null\\n\";			");
				out.println("return strErrMsg;");
				out.println("}");
				out.println("</SCRIPT>");
				out.println("<style type=\"text/css\">");
				out.println("<!--");
				out.println(".style11 {color: #FFFFFF}");
				out.println(".style16 {");
				out.println("color: #000000;");
				out.println("font-weight: bold;");
				out.println("}");
				out.println(".style17 {");
				out.println("color: #660033;");
				out.println("font-weight: bold;");
				out.println("font-size: 18px;");
				out.println("}");
				out.println(".style18 {color: #660033}");
				out.println("-->");
				out.println("</style>");
				out.println("</head>");
				out.println("<body>");
				out.println("<FORM name=mainform method=post>");
				out.println("<div align=\"center\">");
				out.println("<center>");
				out.println("<div align=\"center\">");
				out.println("<center>");
				out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
				out.println("<TBODY>");
				out.println("<TR> ");
				out.println("<TD class=header>              <img src=\"http://localhost:2008/hcutravels/images/frontpage.gif\" width=\"386\" height=\"71\"><img src=\"http://localhost:2008/hcutravels/images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"><img src=\"http://localhost:2008/hcutravels/images/1animated12-thumb[1].gif\" width=\"67\" height=\"50\"></TD>");
				out.println("</TR>");
				out.println("</TBODY>");
				out.println("</TABLE>");
				out.println("</center>");
				out.println("</div>");
				out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
				out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
				out.println("we share a visi<img src=\"http://localhost:2008/hcutravels/images/Animsun.gif\" width=\"60\" height=\"48\">n ");
				out.println("</marquee>");
				out.println("</font></p>");
				out.println("</center>");
				out.println("</div>");
				out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
                out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
                out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
				out.println("Packages </font></a></div></td>");
                out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register Yourself </font></a></div></td>");
                out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
				out.println("Us</font></a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr bgcolor=\"#0000CC\"> ");
                out.println("<td width=\"22%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
				out.println("Accommodation</font></a></div></td>");
                out.println("<td width=\"21%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
				out.println("Traveling Means</font></a></div>");
				out.println("<div align=\"center\"></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
				out.println("Guide</font></a></div></td>");
                out.println("<td width=\"32%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
				out.println("Insurance</font></a></div></td>");
				out.println("</tr>");
				out.println("</table></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<h1 align=\"center\"><font color=\"#660033\">Accomodation Facilities </font></h1>");
				out.println("<table width=\"733\" height=\"500\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
				out.println("<tr> ");
				out.println("<td height=\"33\" colspan=\"2\"><div align=\"center\"><img src=\"http://localhost:2008/hcutravels/images/palmsprings_goa1.jpg\" width=\"155\" height=\"119\"><img src=\"http://localhost:2008/hcutravels/images/north-india-hotels.jpg\" width=\"101\" height=\"119\"><img src=\"http://localhost:2008/hcutravels/images/south-india-hotel.jpg\" width=\"101\" height=\"119\"></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"145\" height=\"453\" valign=\"top\" bgcolor=\"#0099FF\"> ");
				out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/top15.htm\">SomeTop ");
				out.println("Guest houses in India </a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/loginhotel.htm\">Book ");
				out.println("Hotel/Lodging</a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/cancelhotel.htm\">Cancel ");
				out.println("Reservation</a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels ");
				out.println("in India </a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/rates.htm\">Check ");
				out.println("Rates </a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"><div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/faqhotel.htm\">FAQ's</a></div></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<p class=\"style11\"><img src=\"http://localhost:2008/hcutravels/images/raj_banner.gif\" width=\"144\" height=\"148\"></p>");
				out.println("<p class=\"style11\"><img src=\"http://localhost:2008/hcutravels/images/ofl.gif\" width=\"143\" height=\"50\"></p>");
				out.println("<p class=\"style11\">&nbsp;</p></td >");
				out.println("<td width=\"588\"><div align=\"center\"> ");
				out.println("<table width=\"100%\" height=\"453\" border=\"0\">");
				out.println("<tr bgcolor=\"FFCCFF\"> ");
				out.println("<td height=\"63\" colspan=\"2\"><div align=\"center\"><font color=\"#660033\" size=\"5\"><strong>Cancel ");
				out.println("Reservations</strong></font></div></td>");
				out.println("</tr>");
				out.println("<tr bgcolor=\"FFCCFF\"> ");
				out.println("<td colspan=\"2\"><div align=\"center\"><strong><font color=\"#660033\" size=\"5\">Invalid ");
				out.println("Password. Try Again!!!</font></strong></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"47%\" height=\"45\"><div align=\"left\"><strong>Enter Login ");
				out.println("ID</strong></div></td>");
				out.println("<td width=\"53%\"> <input name=\"loginid\" type=\"text\" id=\"loginid2\"> ");
				out.println("</td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td height=\"36\"><div align=\"left\"><strong>Enter Password</strong></div></td>");
				out.println("<td><input name=\"pswd\" type=\"password\" id=\"pswd\"></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td height=\"48\"><div align=\"left\"><strong>Enter Request No.</strong></div></td>");
				out.println("<td> <input name=\"reqno\" type=\"text\" id=\"reqno\"> </td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td colspan=\"2\"><div align=\"center\"> ");
				out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
				out.println("<param name=\"movie\" value=\"http://localhost:2008/hcutravels/images/cancel3.swf\">");
				out.println("<param name=\"quality\" value=\"high\">");
				out.println("<embed src=\"http://localhost:2008/hcutravels/images/cancel3.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"147\" height=\"34\" ></embed> ");
				out.println("</object>");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td height=\"67\" colspan=\"2\">&nbsp;</td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<p align=\"center\">&nbsp;</p>");
				out.println("<hr size=1 width=\"70%\">");
                out.println("<p align=\"center\"><a href=\"http://localhost:2008/hcutravels/top15.htm\">SomeTop Guest houses in India</a>| <a href=\"http://localhost:2008/hcutravels/loginhotel.htm\">Book Hotel/Lodging</a>|<a href=\"http://localhost:2008/hcutravels/cancelhotel.htm\"> Cancel Reservation| </a><a href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels in India</a>|<a href=\"http://localhost:2008/hcutravels/rates.htm\">Check Rates|</a> <a href=\"http://localhost:2008/hcutravels/faqhotel.htm\">FAQ's </a> </p>");
				out.println("<div align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
                out.println("href=\"http://localhost:2008/hcutravels/home.htm\"><FONT ");
				out.println("size=3>Home</FONT></A></FONT></div>");
				out.println("<hr size=1 width=\"70%\">");
				out.println("<p align=\"center\"><img src=\"http://localhost:2008/hcutravels/images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
				out.println("</body>");
				out.println("</html>");
				
            	}
                 else
                 {
                    ResultSet rs1 = st.executeQuery("select * from hotelbooking where reqno =  ("+r+") " ); 
                        
                    if (rs1.next()) 
            	    {
                        
            			out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
						out.println("<html>");
						out.println("<head>");
						out.println("<title>Untitled Document</title>");
						out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
						out.println("<style type=\"text/css\">");
						out.println("<!--");
						out.println(".style11 {color: #FFFFFF}");
						out.println(".style16 {");
						out.println("color: #000000;");
						out.println("font-weight: bold;");
						out.println("}");
						out.println(".style17 {");
						out.println("color: #660033;");
						out.println("font-weight: bold;");
						out.println("font-size: 18px;");
						out.println("}");
						out.println(".style18 {color: #660033}");
						out.println("-->");
						out.println("</style>");
						out.println("</head>");
						out.println("<body>");
						out.println("<div align=\"center\">");
						out.println("<center>");
						out.println("<div align=\"center\">");
						out.println("<center>");
						out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
						out.println("<TBODY>");
						out.println("<TR> ");
						out.println("<TD class=header>              <img src=\"http://localhost:2008/hcutravels/images/frontpage.gif\" width=\"386\" height=\"71\"><img src=\"http://localhost:2008/hcutravels/images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"><img src=\"http://localhost:2008/hcutravels/images/1animated12-thumb[1].gif\" width=\"67\" height=\"50\"></TD>");
						out.println("</TR>");
						out.println("</TBODY>");
						out.println("</TABLE>");
						out.println("</center>");
						out.println("</div>");
						out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
						out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
						out.println("we share a visi<img src=\"http://localhost:2008/hcutravels/images/Animsun.gif\" width=\"60\" height=\"48\">n ");
						out.println("</marquee>");
						out.println("</font></p>");
						out.println("</center>");
						out.println("</div>");
						out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
						out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
                        out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
                        out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
                        out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
						out.println("Packages </font></a></div></td>");
                        out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
                        out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register Yourself </font></a></div></td>");
                        out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
						out.println("Us</font></a></div></td>");
						out.println("</tr>");
						out.println("<tr> ");
						out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
						out.println("<tr bgcolor=\"#0000CC\"> ");
                        out.println("<td width=\"22%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
						out.println("Accommodation</font></a></div></td>");
                        out.println("<td width=\"21%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
						out.println("Traveling Means</font></a></div>");
						out.println("<div align=\"center\"></div></td>");
                        out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
						out.println("Guide</font></a></div></td>");
                        out.println("<td width=\"32%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
						out.println("Insurance</font></a></div></td>");
						out.println("</tr>");
						out.println("</table></td>");
						out.println("</tr>");
						out.println("</table>");
						out.println("<h1 align=\"center\"><font color=\"#660033\">Accomodation Facilities </font></h1>");
						out.println("<table width=\"733\" height=\"400\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
						out.println("<tr> ");
						out.println("<td height=\"33\" colspan=\"2\"><div align=\"center\"><img src=\"http://localhost:2008/hcutravels/images/palmsprings_goa1.jpg\" width=\"155\" height=\"119\"><img src=\"http://localhost:2008/hcutravels/images/north-india-hotels.jpg\" width=\"101\" height=\"119\"><img src=\"http://localhost:2008/hcutravels/images/south-india-hotel.jpg\" width=\"101\" height=\"119\"></div></td>");
						out.println("</tr>");
						out.println("<tr> ");
						out.println("<td width=\"145\" height=\"345\" valign=\"top\" bgcolor=\"#0099FF\"> ");
						out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
						out.println("<tr> ");
                        out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/top15.htm\">SomeTop ");
						out.println("Guest houses in India </a></div></td>");
						out.println("</tr>");
						out.println("<tr> ");
                        out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/loginhotel.htm\">Book ");
						out.println("Hotel/Lodging</a></div></td>");
						out.println("</tr>");
						out.println("<tr> ");
                        out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/cancelhotel.htm\">Cancel ");
						out.println("Reservation</a></div></td>");
						out.println("</tr>");
						out.println("<tr> ");
						out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels ");
						out.println("in India </a></div></td>");
						out.println("</tr>");
						out.println("<tr> ");
                        out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/rates.htm\">Check ");
						out.println("Rates </a></div></td>");
						out.println("</tr>");
						out.println("<tr> ");
                        out.println("<td height=\"19\" bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/faqhotel.htm\">FAQ's</a></div></td>");
						out.println("</tr>");
						out.println("</table>");
						out.println("<p class=\"style11\">&nbsp;</p>");
						out.println("<p class=\"style11\"><img src=\"http://localhost:2008/hcutravels/images/raj_banner.gif\" width=\"145\" height=\"145\"></p>");
						out.println("<p class=\"style11\">&nbsp;</p></td >");
						out.println("<td width=\"588\"> <div align=\"left\"> ");
						out.println("<table width=\"100%\" height=\"368\" border=\"0\">");
						out.println("<tr bgcolor=\"FFCCFF\"> ");
						out.println("<td height=\"58\"> <div align=\"center\"><font color=\"#660066\" size=\"5\"><strong><img src=\"http://localhost:2008/hcutravels/images/Cross.gif\" width=\"49\" height=\"30\">Cancelled</strong></font></div></td>");
						out.println("</tr>");
						out.println("<tr> ");
						out.println("<td><div align=\"center\">");
						out.println("<p><strong><font color=\"#660033\" size=\"5\">Your reservation corresponding ");
						out.println("to </font></strong></p>");
						out.println("<p><strong><font color=\"#660033\" size=\"5\">request no. "+reqno+" has ");
						out.println("been cancelled. </font></strong></p>");
						out.println("<p><strong><font color=\"#660033\" size=\"5\">Your cancellation details ");
						out.println("will be send to you </font></strong></p>");
						out.println("<p><strong><font color=\"#660033\" size=\"5\">within 2days.</font></strong></p>");
						out.println("</div></td>");
						out.println("</tr>");
						out.println("</table>");
						out.println("</div></td>");
						out.println("</tr>");
						out.println("</table>");
						out.println("<p align=\"center\">&nbsp;</p>");
						out.println("<hr size=1 width=\"70%\">");
                        out.println("<p align=\"center\"><a href=\"http://localhost:2008/hcutravels/top15.htm\">SomeTop Guest houses in India</a>| <a href=\"http://localhost:2008/hcutravels/loginhotel.htm\">Book Hotel/Lodging</a>|<a href=\"http://localhost:2008/hcutravels/cancelhotel.htm\"> Cancel Reservation| </a><a href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels in India</a>|<a href=\"http://localhost:2008/hcutravels/rates.htm\">Check Rates|</a> <a href=\"http://localhost:2008/hcutravels/faqhotel.htm\">FAQ's </a> </p>");
						out.println("<div align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
                        out.println("href=\"http://localhost:2008/hcutravels/home.htm\"><FONT ");
						out.println("size=3>Home</FONT></A></FONT></div>");
						out.println("<hr size=1 width=\"70%\">");
						out.println("<p align=\"center\"><img src=\"http://localhost:2008/hcutravels/images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
						out.println("</body>");
						out.println("</html>");
                        st.executeQuery("delete from hotelbooking where reqno =  ("+r+") " );   
                        
						
}
            else
            {
                   out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
				out.println("<html>");
				out.println("<head>");
				out.println("<title>Untitled Document</title>");
				out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
				out.println("<SCRIPT>");
				out.println("/*function doClear()");
				out.println("{		 ");
				out.println("document.mainform.loginid.value =\"\"");
				out.println("document.mainform.password.value = \"\";");
				out.println("}*/");
				out.println("function doSubmit()");
				out.println("{");
				out.println("var strErrMsg;");
				out.println("strErrMsg = \"\";			");
				out.println("strErrMsg = doValidations();");
				out.println("if (strErrMsg == \"\" )");
				out.println("{				");
				out.println("document.mainform.action = \"http://localhost:2008/examples/servlet/cancelhotel2\";		");
				out.println("document.mainform.submit();");
				out.println("}");
				out.println("else");
				out.println("{alert(strErrMsg);}");
				out.println("}");
				out.println("function doValidations()");
				out.println("{");
				out.println("var strFld;");
				out.println("var frmDoc;");
				out.println("var strErrMsg;");
				out.println("strErrMsg = \"\";");
				out.println("frmDoc = document.mainform;			");
				out.println("strFld = frmDoc.loginid");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"login-id can not be null\\n\";			");
				out.println("strFld = frmDoc.pswd");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"password can not be null\\n\";	");
				out.println("strFld = frmDoc.reqno");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"req-no can not be null\\n\";			");
				out.println("return strErrMsg;");
				out.println("}");
				out.println("</SCRIPT>");
				out.println("<style type=\"text/css\">");
				out.println("<!--");
				out.println(".style11 {color: #FFFFFF}");
				out.println(".style16 {");
				out.println("color: #000000;");
				out.println("font-weight: bold;");
				out.println("}");
				out.println(".style17 {");
				out.println("color: #660033;");
				out.println("font-weight: bold;");
				out.println("font-size: 18px;");
				out.println("}");
				out.println(".style18 {color: #660033}");
				out.println("-->");
				out.println("</style>");
				out.println("</head>");
				out.println("<body>");
				out.println("<FORM name=mainform method=post>");
				out.println("<div align=\"center\">");
				out.println("<center>");
				out.println("<div align=\"center\">");
				out.println("<center>");
				out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
				out.println("<TBODY>");
				out.println("<TR> ");
				out.println("<TD class=header>              <img src=\"http://localhost:2008/hcutravels/images/frontpage.gif\" width=\"386\" height=\"71\"><img src=\"http://localhost:2008/hcutravels/images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"><img src=\"http://localhost:2008/hcutravels/images/1animated12-thumb[1].gif\" width=\"67\" height=\"50\"></TD>");
				out.println("</TR>");
				out.println("</TBODY>");
				out.println("</TABLE>");
				out.println("</center>");
				out.println("</div>");
				out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
				out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
				out.println("we share a visi<img src=\"http://localhost:2008/hcutravels/images/Animsun.gif\" width=\"60\" height=\"48\">n ");
				out.println("</marquee>");
				out.println("</font></p>");
				out.println("</center>");
				out.println("</div>");
				out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
                out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
                out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
				out.println("Packages </font></a></div></td>");
                out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register Yourself </font></a></div></td>");
                out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
				out.println("Us</font></a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr bgcolor=\"#0000CC\"> ");
                out.println("<td width=\"22%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
				out.println("Accommodation</font></a></div></td>");
                out.println("<td width=\"21%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
				out.println("Traveling Means</font></a></div>");
				out.println("<div align=\"center\"></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
				out.println("Guide</font></a></div></td>");
                out.println("<td width=\"32%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
				out.println("Insurance</font></a></div></td>");
				out.println("</tr>");
				out.println("</table></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<h1 align=\"center\"><font color=\"#660033\">Accomodation Facilities </font></h1>");
				out.println("<table width=\"733\" height=\"500\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
				out.println("<tr> ");
				out.println("<td height=\"33\" colspan=\"2\"><div align=\"center\"><img src=\"http://localhost:2008/hcutravels/images/palmsprings_goa1.jpg\" width=\"155\" height=\"119\"><img src=\"http://localhost:2008/hcutravels/images/north-india-hotels.jpg\" width=\"101\" height=\"119\"><img src=\"http://localhost:2008/hcutravels/images/south-india-hotel.jpg\" width=\"101\" height=\"119\"></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"145\" height=\"453\" valign=\"top\" bgcolor=\"#0099FF\"> ");
				out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/top15.htm\">SomeTop ");
				out.println("Guest houses in India </a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/loginhotel.htm\">Book ");
				out.println("Hotel/Lodging</a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/cancelhotel.htm\">Cancel ");
				out.println("Reservation</a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels ");
				out.println("in India </a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/rates.htm\">Check ");
				out.println("Rates </a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"><div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/faqhotel.htm\">FAQ's</a></div></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<p class=\"style11\"><img src=\"http://localhost:2008/hcutravels/images/raj_banner.gif\" width=\"144\" height=\"148\"></p>");
				out.println("<p class=\"style11\"><img src=\"http://localhost:2008/hcutravels/images/ofl.gif\" width=\"143\" height=\"50\"></p>");
				out.println("<p class=\"style11\">&nbsp;</p></td >");
				out.println("<td width=\"588\"><div align=\"center\"> ");
				out.println("<table width=\"100%\" height=\"453\" border=\"0\">");
				out.println("<tr bgcolor=\"FFCCFF\"> ");
				out.println("<td height=\"63\" colspan=\"2\"><div align=\"center\"><font color=\"#660033\" size=\"5\"><strong>Cancel ");
				out.println("Reservations</strong></font></div></td>");
				out.println("</tr>");
				out.println("<tr bgcolor=\"FFCCFF\"> ");
				out.println("<td colspan=\"2\"><div align=\"center\"><strong><font color=\"#660033\" size=\"5\">Invalid ");
				out.println("Request No. Try Again!!!</font></strong></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"47%\" height=\"45\"><div align=\"left\"><strong>Enter Login ");
				out.println("ID</strong></div></td>");
				out.println("<td width=\"53%\"> <input name=\"loginid\" type=\"text\" id=\"loginid2\"> ");
				out.println("</td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td height=\"36\"><div align=\"left\"><strong>Enter Password</strong></div></td>");
				out.println("<td><input name=\"pswd\" type=\"password\" id=\"pswd\"></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td height=\"48\"><div align=\"left\"><strong>Enter Request No.</strong></div></td>");
				out.println("<td> <input name=\"reqno\" type=\"text\" id=\"reqno\"> </td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td colspan=\"2\"><div align=\"center\"> ");
				out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
				out.println("<param name=\"movie\" value=\"http://localhost:2008/hcutravels/images/cancel3.swf\">");
				out.println("<param name=\"quality\" value=\"high\">");
				out.println("<embed src=\"http://localhost:2008/hcutravels/images/cancel3.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"147\" height=\"34\" ></embed> ");
				out.println("</object>");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td height=\"67\" colspan=\"2\">&nbsp;</td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<p align=\"center\">&nbsp;</p>");
				out.println("<hr size=1 width=\"70%\">");
                out.println("<p align=\"center\"><a href=\"http://localhost:2008/hcutravels/top15.htm\">SomeTop Guest houses in India</a>| <a href=\"http://localhost:2008/hcutravels/loginhotel.htm\">Book Hotel/Lodging</a>|<a href=\"http://localhost:2008/hcutravels/cancelhotel.htm\"> Cancel Reservation| </a><a href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels in India</a>|<a href=\"http://localhost:2008/hcutravels/rates.htm\">Check Rates|</a> <a href=\"http://localhost:2008/hcutravels/faqhotel.htm\">FAQ's </a> </p>");
				out.println("<div align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
                out.println("href=\"http://localhost:2008/hcutravels/home.htm\"><FONT ");
				out.println("size=3>Home</FONT></A></FONT></div>");
				out.println("<hr size=1 width=\"70%\">");
				out.println("<p align=\"center\"><img src=\"http://localhost:2008/hcutravels/images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
				out.println("</body>");
				out.println("</html>");
				

}
				
            	}
            }
            else
            {
            	out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
				out.println("<html>");
				out.println("<head>");
				out.println("<title>Untitled Document</title>");
				out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
				out.println("<SCRIPT>");
				out.println("/*function doClear()");
				out.println("{		 ");
				out.println("document.mainform.loginid.value =\"\"");
				out.println("document.mainform.password.value = \"\";");
				out.println("}*/");
				out.println("function doSubmit()");
				out.println("{");
				out.println("var strErrMsg;");
				out.println("strErrMsg = \"\";			");
				out.println("strErrMsg = doValidations();");
				out.println("if (strErrMsg == \"\" )");
				out.println("{				");
				out.println("document.mainform.action = \"http://localhost:2008/examples/servlet/cancelhotel2\";		");
				out.println("document.mainform.submit();");
				out.println("}");
				out.println("else");
				out.println("{alert(strErrMsg);}");
				out.println("}");
				out.println("function doValidations()");
				out.println("{");
				out.println("var strFld;");
				out.println("var frmDoc;");
				out.println("var strErrMsg;");
				out.println("strErrMsg = \"\";");
				out.println("frmDoc = document.mainform;			");
				out.println("strFld = frmDoc.loginid");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"login-id can not be null\\n\";			");
				out.println("strFld = frmDoc.pswd");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"password can not be null\\n\";	");
				out.println("strFld = frmDoc.reqno");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"req-no can not be null\\n\";			");
				out.println("return strErrMsg;");
				out.println("}");
				out.println("</SCRIPT>");
				out.println("<style type=\"text/css\">");
				out.println("<!--");
				out.println(".style11 {color: #FFFFFF}");
				out.println(".style16 {");
				out.println("color: #000000;");
				out.println("font-weight: bold;");
				out.println("}");
				out.println(".style17 {");
				out.println("color: #660033;");
				out.println("font-weight: bold;");
				out.println("font-size: 18px;");
				out.println("}");
				out.println(".style18 {color: #660033}");
				out.println("-->");
				out.println("</style>");
				out.println("</head>");
				out.println("<body>");
				out.println("<FORM name=mainform method=post>");
				out.println("<div align=\"center\">");
				out.println("<center>");
				out.println("<div align=\"center\">");
				out.println("<center>");
				out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
				out.println("<TBODY>");
				out.println("<TR> ");
				out.println("<TD class=header>              <img src=\"http://localhost:2008/hcutravels/images/frontpage.gif\" width=\"386\" height=\"71\"><img src=\"http://localhost:2008/hcutravels/images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"><img src=\"http://localhost:2008/hcutravels/images/1animated12-thumb[1].gif\" width=\"67\" height=\"50\"></TD>");
				out.println("</TR>");
				out.println("</TBODY>");
				out.println("</TABLE>");
				out.println("</center>");
				out.println("</div>");
				out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
				out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
				out.println("we share a visi<img src=\"http://localhost:2008/hcutravels/images/Animsun.gif\" width=\"60\" height=\"48\">n ");
				out.println("</marquee>");
				out.println("</font></p>");
				out.println("</center>");
				out.println("</div>");
				out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
                out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
                out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
				out.println("Packages </font></a></div></td>");
                out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register Yourself </font></a></div></td>");
                out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
				out.println("Us</font></a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr bgcolor=\"#0000CC\"> ");
                out.println("<td width=\"22%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
				out.println("Accommodation</font></a></div></td>");
                out.println("<td width=\"21%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
				out.println("Traveling Means</font></a></div>");
				out.println("<div align=\"center\"></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
				out.println("Guide</font></a></div></td>");
                out.println("<td width=\"32%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"http://localhost:2008/hcutravels/travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
				out.println("Insurance</font></a></div></td>");
				out.println("</tr>");
				out.println("</table></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<h1 align=\"center\"><font color=\"#660033\">Accomodation Facilities </font></h1>");
				out.println("<table width=\"733\" height=\"500\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
				out.println("<tr> ");
				out.println("<td height=\"33\" colspan=\"2\"><div align=\"center\"><img src=\"http://localhost:2008/hcutravels/images/palmsprings_goa1.jpg\" width=\"155\" height=\"119\"><img src=\"http://localhost:2008/hcutravels/images/north-india-hotels.jpg\" width=\"101\" height=\"119\"><img src=\"http://localhost:2008/hcutravels/images/south-india-hotel.jpg\" width=\"101\" height=\"119\"></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"145\" height=\"453\" valign=\"top\" bgcolor=\"#0099FF\"> ");
				out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/top15.htm\">SomeTop ");
				out.println("Guest houses in India </a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/loginhotel.htm\">Book ");
				out.println("Hotel/Lodging</a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/cancelhotel.htm\">Cancel ");
				out.println("Reservation</a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels ");
				out.println("in India </a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/rates.htm\">Check ");
				out.println("Rates </a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"><div align=\"center\" class=\"style16\"><a href=\"http://localhost:2008/hcutravels/faqhotel.htm\">FAQ's</a></div></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<p class=\"style11\"><img src=\"http://localhost:2008/hcutravels/images/raj_banner.gif\" width=\"144\" height=\"148\"></p>");
				out.println("<p class=\"style11\"><img src=\"http://localhost:2008/hcutravels/images/ofl.gif\" width=\"143\" height=\"50\"></p>");
				out.println("<p class=\"style11\">&nbsp;</p></td >");
				out.println("<td width=\"588\"><div align=\"center\"> ");
				out.println("<table width=\"100%\" height=\"453\" border=\"0\">");
				out.println("<tr bgcolor=\"FFCCFF\"> ");
				out.println("<td height=\"63\" colspan=\"2\"><div align=\"center\"><font color=\"#660033\" size=\"5\"><strong>Cancel ");
				out.println("Reservations</strong></font></div></td>");
				out.println("</tr>");
				out.println("<tr bgcolor=\"FFCCFF\"> ");
				out.println("<td colspan=\"2\"><div align=\"center\"><strong><font color=\"#660033\" size=\"5\">Invalid ");
				out.println("LoginID. Try Again!!!</font></strong></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"47%\" height=\"45\"><div align=\"left\"><strong>Enter Login ");
				out.println("ID</strong></div></td>");
				out.println("<td width=\"53%\"> <input name=\"loginid\" type=\"text\" id=\"loginid2\"  > ");
				out.println("</td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td height=\"36\"><div align=\"left\"><strong>Enter Password</strong></div></td>");
				out.println("<td><input name=\"pswd\" type=\"password\" id=\"pswd\"></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td height=\"48\"><div align=\"left\"><strong>Enter Request No.</strong></div></td>");
				out.println("<td> <input name=\"reqno\" type=\"text\" id=\"reqno\"> </td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td colspan=\"2\"><div align=\"center\"> ");
				out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
				out.println("<param name=\"movie\" value=\"http://localhost:2008/hcutravels/images/cancel3.swf\">");
				out.println("<param name=\"quality\" value=\"high\">");
				out.println("<embed src=\"http://localhost:2008/hcutravels/images/cancel3.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"147\" height=\"34\" ></embed> ");
				out.println("</object>");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td height=\"67\" colspan=\"2\">&nbsp;</td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<p align=\"center\">&nbsp;</p>");
				out.println("<hr size=1 width=\"70%\">");
                out.println("<p align=\"center\"><a href=\"http://localhost:2008/hcutravels/top15.htm\">SomeTop Guest houses in India</a>| <a href=\"http://localhost:2008/hcutravels/loginhotel.htm\">Book Hotel/Lodging</a>|<a href=\"http://localhost:2008/hcutravels/cancelhotel.htm\"> Cancel Reservation| </a><a href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels in India</a>|<a href=\"http://localhost:2008/hcutravels/rates.htm\">Check Rates|</a> <a href=\"http://localhost:2008/hcutravels/faqhotel.htm\">FAQ's </a> </p>");
				out.println("<div align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
                out.println("href=\"http://localhost:2008/hcutravels/home.htm\"><FONT ");
				out.println("size=3>Home</FONT></A></FONT></div>");
				out.println("<hr size=1 width=\"70%\">");
				out.println("<p align=\"center\"><img src=\"http://localhost:2008/hcutravels/images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
				out.println("</body>");
				out.println("</html>");
				
				
            }
            }catch(Exception e){
            	out.println("Exception"+e.getMessage()+e.toString());
            }
            finally{
            	try{
            		if(c!=null)
            			c.close();
            	}catch(Exception e){
            		out.println("Exception closing the connection"+e.getMessage());
            	}
            }
   		}
   }
   
